server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
  ssl:
    enabled: false
   # key-alias: kite2
   # key-store: classpath:keystore/keystore.p12
   # key-store-type: PKCS12
   # key-store-password: REDACTED_PASSWORD
  tomcat:
    accesslog:
      enabled: true
      directory: logs
      prefix: access_log
      suffix: .log
      file-date-format: .yyyy-MM-dd
spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/registration?charSet=UTF8
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        connection:
          charSet: UTF-8
    show-sql: true
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file:
    path: ./log

management:
  endpoints:
    web:
      exposure:
        include: "*"

openai:
  api:
    key: ${OPENAI_API_KEY}         # kommt aus .env
  model: ${OPENAI_MODEL:gpt-4o}    # Fallback, falls nicht in .env
  temperature: ${OPENAI_TEMPERATURE:0.5}
  max-tokens: ${OPENAI_MAX_TOKENS:2000}



security:
  api:
    username: ${API_USERNAME:KiteRoot}
    password: ${API_PASSWORD:ChangeMe123!}

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      filter-method: auto
      filter-order: 1
      url: /metrics/(playthroughs/hit|scenes/.*/hit)
      strategy: first
      rate-limits:
        - expression: "getRemoteAddr()"
          bandwidths:
            - capacity: 30
              time: 1
              unit: minutes
              refill-strategy: greedy