package com.hhn.kite2server.data;

import lombok.*;

/**
 * Request record for adding a new interaction data object.
 * @param prompt The input text provided by the user.
 * @param completion The response text generated by the AI.
 */
public record AddDataObjectRequest(
    String prompt,
    String completion
){}
